# Generated by Django 2.2 on 2019-06-12 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20190612_0147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='played',
            name='won',
        ),
    ]
