# Generated by Django 2.2 on 2019-06-12 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_remove_played_won'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='played',
            options={'ordering': ['-date']},
        ),
    ]
