# Generated by Django 2.2 on 2019-06-12 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20190612_0240'),
    ]

    operations = [
        migrations.AddField(
            model_name='played',
            name='won',
            field=models.BooleanField(default=True),
        ),
    ]
